spring:
    datasource:
        generate-unique-name: false
        hikari:
            maximum-pool-size: 4
            auto-commit: false
            connection-timeout: 250
        
        url: jdbc:postgresql://localhost:5432/springboot
        username: lect
        password: prac
